#  THIS FILE ALWAYS READ THE .ENV FILE ${}

version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${BD_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data